/* ============================================================
   Score Automator — Excel Export (excel.js)
   Requires SheetJS (XLSX) to be loaded before this script
   ============================================================ */

(function () {
  'use strict';

  function exportToExcel(config, student, scoreResult, feedbackText, additionalComments) {
    if (typeof XLSX === 'undefined') {
      alert('Excel library not loaded. Please check your internet connection and try again.');
      return;
    }

    const wb = XLSX.utils.book_new();

    /* ── Sheet 1: Results ──────────────────────────────────── */
    const R = [];

    // Header
    R.push([config.assessmentTitle || 'Assessment', '', config.courseName || '', '', config.universityName || '']);
    R.push([config.assignmentInfo || '']);
    R.push([`Version: ${config.version || '1.0'}`, '', '', '', `Date: ${SA.formatDate()}`]);
    R.push([]);

    // Student details
    R.push(['Student Name', student.name || '', 'Student ID', student.id || '', 'Tutor', student.tutor || '']);
    R.push([]);

    // Criteria table header
    R.push(['Criterion', 'Weight (%)', 'Grade', 'Midpoint', 'Override', 'Final Score (/100)', 'Weighted', 'Tier']);

    let weightCheck = 0;
    for (const row of scoreResult.rows) {
      if (!row.grade) continue;
      weightCheck += row.criterion.weight;
      R.push([
        row.criterion.name,
        row.criterion.weight,
        row.grade,
        row.midpoint,
        row.override !== null ? row.override : '',
        row.finalScore,
        parseFloat(row.weightedScore.toFixed(2)),
        SA.TIER_LABELS[row.tier] || row.tier
      ]);
    }

    R.push([]);
    R.push(['', '', '', '', '', 'Weighted Score /100', parseFloat(scoreResult.weightedTotal.toFixed(2))]);

    if (config.enableLatePenalties && scoreResult.latePenalty) {
      const lp = scoreResult.latePenalty;
      if (lp.deduction > 0 || lp.fail) {
        R.push(['', '', '', '', '', `Late Penalty (${lp.label})`, lp.fail ? 'Fail' : `-${lp.deduction}%`]);
        R.push(['', '', '', '', '', 'Penalised Score /100', parseFloat(scoreResult.penalisedScore.toFixed(2))]);
      }
    }

    R.push([]);
    R.push(['', '', '', '', '', 'Suggested Grade', scoreResult.suggestedGrade]);
    R.push([]);

    // Feedback
    R.push(['COOKED FEEDBACK']);
    R.push([feedbackText]);
    R.push([]);

    if (additionalComments && additionalComments.trim()) {
      R.push(["MARKER'S NOTES"]);
      R.push([additionalComments]);
      R.push([]);
    }

    const wsResults = XLSX.utils.aoa_to_sheet(R);
    wsResults['!cols'] = [
      { wch: 30 }, { wch: 10 }, { wch: 8 }, { wch: 10 },
      { wch: 10 }, { wch: 16 }, { wch: 12 }, { wch: 28 }
    ];
    XLSX.utils.book_append_sheet(wb, wsResults, 'Results');

    /* ── Sheet 2: Rubric ───────────────────────────────────── */
    const RUB = [];
    RUB.push(['RUBRIC — ' + (config.assessmentTitle || 'Assessment')]);
    RUB.push([]);
    RUB.push(['Criterion', 'Weight (%)',
              'Excellent (A+ / A / A-)',
              'Proficient (B+ / B / B-)',
              'Developing (C+ / C / C-)',
              'Unsatisfactory (D)']);

    for (const c of config.criteria) {
      RUB.push([
        c.name, c.weight,
        c.rubric.excellent      || '',
        c.rubric.proficient     || '',
        c.rubric.developing     || '',
        c.rubric.unsatisfactory || ''
      ]);
    }

    const wsRubric = XLSX.utils.aoa_to_sheet(RUB);
    wsRubric['!cols'] = [
      { wch: 28 }, { wch: 10 },
      { wch: 45 }, { wch: 45 }, { wch: 45 }, { wch: 45 }
    ];
    XLSX.utils.book_append_sheet(wb, wsRubric, 'Rubric');

    /* ── Sheet 3: Grade Feedback ───────────────────────────── */
    const GF = [];
    GF.push(['GRADE FEEDBACK TEMPLATES']);
    GF.push([]);
    GF.push(['Grade', 'Intro Paragraph', 'Outro Paragraph']);

    for (const gf of config.gradeFeedback) {
      GF.push([gf.grade, gf.intro, gf.outro]);
    }

    const wsGF = XLSX.utils.aoa_to_sheet(GF);
    wsGF['!cols'] = [{ wch: 8 }, { wch: 70 }, { wch: 70 }];
    XLSX.utils.book_append_sheet(wb, wsGF, 'Grade Feedback');

    /* ── Sheet 4: Instructions ─────────────────────────────── */
    const INS = [];
    INS.push(['Score Automator — Instructions']);
    INS.push([]);
    INS.push(['This workbook was generated by Score Automator (marking.stephendmann.com)']);
    INS.push([]);
    INS.push(['Sheet', 'Contents']);
    INS.push(['Results', 'The student\'s grades, scores, and generated feedback for this submission.']);
    INS.push(['Rubric', 'The rubric descriptors for each criterion and tier.']);
    INS.push(['Grade Feedback', 'The intro and outro paragraphs used for each overall grade.']);
    INS.push([]);
    INS.push(['Scorer:', config.name || 'Unnamed Scorer']);
    INS.push(['Assessment:', config.assessmentTitle || '']);
    INS.push(['Course:', config.courseName || '']);
    INS.push(['University:', config.universityName || '']);
    INS.push(['Generated:', SA.formatDate()]);

    const wsIns = XLSX.utils.aoa_to_sheet(INS);
    wsIns['!cols'] = [{ wch: 20 }, { wch: 70 }];
    XLSX.utils.book_append_sheet(wb, wsIns, 'Instructions');

    /* ── Write file ────────────────────────────────────────── */
    const safeName    = (student.name || 'Student').replace(/[^a-zA-Z0-9 ]/g, '_').trim();
    const safeCourse  = (config.courseName || 'Assessment').replace(/[^a-zA-Z0-9]/g, '_');
    XLSX.writeFile(wb, `${safeName}_${safeCourse}_Feedback.xlsx`);
  }

  window.SAExcel = { exportToExcel };
})();
