/* ============================================================
   Score Automator — Excel Export (excel.js)
   Requires SheetJS (XLSX) to be loaded before this script
   ============================================================ */

(function () {
  'use strict';

  function exportToExcel(config, student, scoreResult, feedbackText, additionalComments) {
    if (typeof XLSX === 'undefined') {
      alert('Excel library not loaded. Please check your internet connection and try again.');
      return;
    }

    const wb = XLSX.utils.book_new();

    /* ── Sheet 1: Results ──────────────────────────────────── */
    const R = [];

    // Header
    R.push([config.assessmentTitle || 'Assessment', '', config.courseName || '', '', config.universityName || '']);
    R.push([config.assignmentInfo || '']);
    R.push([`Scorer Version: ${config.version || '1.0'}`, '', `App Version: ${config.appVersion || '2.0'}`, '', `Date: ${SA.formatDate()}`]);
    R.push([]);

    // Student details
    R.push(['Student Name', student.name || '', 'Student ID', student.id || '', 'Tutor', student.tutor || '']);
    R.push([]);

    // Criteria table header
    R.push(['Criterion', 'Weight (%)', 'Grade', 'Midpoint', 'Override', 'Final Score (/100)', 'Weighted', 'Tier']);

    const rounding = config.scoreRounding || 'none';
    let weightCheck = 0;
    for (const row of scoreResult.rows) {
      if (!row.grade) continue;
      weightCheck += row.criterion.weight;
      R.push([
        row.criterion.name,
        row.criterion.weight,
        row.grade,
        row.midpoint,
        row.override !== null ? row.override : '',
        row.finalScore,
        parseFloat(SA.formatScore(row.weightedScore, rounding)),
        SA.getTierLabel(config, row.tier, { withRange: true })
      ]);
    }

    R.push([]);
    R.push(['', '', '', '', '', 'Weighted Score /100', parseFloat(SA.formatScore(scoreResult.weightedTotal, rounding))]);

    if (config.enableLatePenalties && scoreResult.latePenalty) {
      const lp = scoreResult.latePenalty;
      if (lp.deduction > 0 || lp.fail) {
        R.push(['', '', '', '', '', `Late Penalty (${lp.label})`, lp.fail ? 'Fail' : `-${lp.deduction}%`]);
        R.push(['', '', '', '', '', 'Penalised Score /100', parseFloat(SA.formatScore(scoreResult.penalisedScore, rounding))]);
      }
    }

    R.push([]);
    R.push(['', '', '', '', '', 'Suggested Grade', scoreResult.suggestedGrade]);
    R.push([]);

    // Feedback
    R.push(['COOKED FEEDBACK']);
    R.push([feedbackText]);
    R.push([]);

    if (additionalComments && additionalComments.trim()) {
      R.push(["MARKER'S NOTES"]);
      R.push([additionalComments]);
      R.push([]);
    }

    const wsResults = XLSX.utils.aoa_to_sheet(R);
    wsResults['!cols'] = [
      { wch: 30 }, { wch: 10 }, { wch: 8 }, { wch: 10 },
      { wch: 10 }, { wch: 16 }, { wch: 12 }, { wch: 28 }
    ];
    XLSX.utils.book_append_sheet(wb, wsResults, 'Results');

    /* ── Sheet 2: Rubric ───────────────────────────────────── */
    const RUB = [];
    RUB.push(['RUBRIC — ' + (config.assessmentTitle || 'Assessment')]);
    RUB.push([]);
    RUB.push(['Criterion', 'Weight (%)',
              SA.getTierLabel(config, 'excellent',      { withRange: true }),
              SA.getTierLabel(config, 'proficient',     { withRange: true }),
              SA.getTierLabel(config, 'developing',     { withRange: true }),
              SA.getTierLabel(config, 'satisfactory',   { withRange: true }),
              SA.getTierLabel(config, 'unsatisfactory', { withRange: true })]);

    for (const c of config.criteria) {
      RUB.push([
        c.name, c.weight,
        c.rubric.excellent      || '',
        c.rubric.proficient     || '',
        c.rubric.developing     || '',
        c.rubric.satisfactory   || '',
        c.rubric.unsatisfactory || ''
      ]);
    }

    const wsRubric = XLSX.utils.aoa_to_sheet(RUB);
    wsRubric['!cols'] = [
      { wch: 28 }, { wch: 10 },
      { wch: 45 }, { wch: 45 }, { wch: 45 }, { wch: 45 }, { wch: 45 }
    ];
    XLSX.utils.book_append_sheet(wb, wsRubric, 'Rubric');

    /* ── Sheet 3: Grade Feedback ───────────────────────────── */
    const GF = [];
    GF.push(['GRADE FEEDBACK TEMPLATES']);
    GF.push([]);
    GF.push(['Grade', 'Intro Paragraph', 'Outro Paragraph']);

    for (const gf of config.gradeFeedback) {
      GF.push([gf.grade, gf.intro, gf.outro]);
    }

    const wsGF = XLSX.utils.aoa_to_sheet(GF);
    wsGF['!cols'] = [{ wch: 8 }, { wch: 70 }, { wch: 70 }];
    XLSX.utils.book_append_sheet(wb, wsGF, 'Grade Feedback');

    /* ── Sheet 4: Instructions ─────────────────────────────── */
    const INS = [];
    INS.push(['Feedback Kitchen — Instructions']);
    INS.push(['App Version: ' + (config.appVersion || '2.0')]);
    INS.push([]);
    INS.push(['This workbook was generated by Feedback Kitchen v' + (config.appVersion || '2.0') + ' (marking.stephendmann.com)']);
    INS.push([]);
    INS.push(['Sheet', 'Contents']);
    INS.push(['Results', 'The student\'s grades, scores, and generated feedback for this submission.']);
    INS.push(['Rubric', 'The rubric descriptors for each criterion and tier.']);
    INS.push(['Grade Feedback', 'The intro and outro paragraphs used for each overall grade.']);
    INS.push([]);
    INS.push(['Scorer:', config.name || 'Unnamed Scorer']);
    INS.push(['Assessment:', config.assessmentTitle || '']);
    INS.push(['Course:', config.courseName || '']);
    INS.push(['University:', config.universityName || '']);
    INS.push(['Generated:', SA.formatDate()]);

    const wsIns = XLSX.utils.aoa_to_sheet(INS);
    wsIns['!cols'] = [{ wch: 20 }, { wch: 70 }];
    XLSX.utils.book_append_sheet(wb, wsIns, 'Instructions');

    /* ── Write file ────────────────────────────────────────── */
    const safeName    = (student.name || 'Student').replace(/[^a-zA-Z0-9 ]/g, '_').trim();
    const safeCourse  = (config.courseName || 'Assessment').replace(/[^a-zA-Z0-9]/g, '_');
    XLSX.writeFile(wb, `${safeName}_${safeCourse}_Feedback.xlsx`);
  }

  /* ══════════════════════════════════════════════════════════
     COHORT EXPORT — multi-student workbook
     ══════════════════════════════════════════════════════════ */
  function exportCohortToExcel(config, cohort) {
    if (typeof XLSX === 'undefined') {
      alert('Excel library not loaded. Please check your internet connection and try again.');
      return false;
    }
    if (!cohort || !cohort.students || cohort.students.length === 0) {
      alert('No students in this cohort yet.');
      return false;
    }

    const wb = XLSX.utils.book_new();
    const rounding = config.scoreRounding || 'none';
    const criteria = config.criteria;

    /* ── Sheet 1: Cohort Summary ──────────────────────────── */
    const SUM = [];
    SUM.push(['COHORT SUMMARY — ' + (cohort.label || 'Cohort')]);
    SUM.push([]);
    SUM.push(['Scorer:',      config.name || '']);
    SUM.push(['Assessment:',  config.assessmentTitle || '']);
    SUM.push(['Course:',      config.courseName || '']);
    SUM.push(['University:',  config.universityName || '']);
    SUM.push(['App version:', config.appVersion || '2.0']);
    SUM.push(['Scorer version:', config.version || '1.0']);
    SUM.push(['Cohort label:', cohort.label || '']);
    SUM.push(['Multiple markers:', cohort.multiMarker ? 'Yes' : 'No']);
    SUM.push(['Students in cohort:', cohort.students.length]);
    SUM.push(['Cohort started:', cohort.createdAt ? new Date(cohort.createdAt).toLocaleString('en-NZ') : '']);
    SUM.push(['Exported:', SA.formatDate() + ' ' + new Date().toLocaleTimeString('en-NZ')]);
    SUM.push([]);

    // Class distribution — average per criterion, class mean
    const totals = cohort.students.map(s => {
      const wt = (s.scoreResult && typeof s.scoreResult.weightedTotal === 'number')
                   ? s.scoreResult.weightedTotal : 0;
      return wt;
    });
    const penalised = cohort.students.map(s => {
      const p = (s.scoreResult && typeof s.scoreResult.penalisedScore === 'number')
                  ? s.scoreResult.penalisedScore : 0;
      return p;
    });
    const avg = arr => arr.length ? (arr.reduce((a,b) => a+b, 0) / arr.length) : 0;
    const min = arr => arr.length ? Math.min.apply(null, arr) : 0;
    const max = arr => arr.length ? Math.max.apply(null, arr) : 0;

    SUM.push(['CLASS STATISTICS (pre-penalty)']);
    SUM.push(['Mean weighted total:', parseFloat(SA.formatScore(avg(totals), rounding))]);
    SUM.push(['Min weighted total:',  parseFloat(SA.formatScore(min(totals), rounding))]);
    SUM.push(['Max weighted total:',  parseFloat(SA.formatScore(max(totals), rounding))]);
    SUM.push([]);
    SUM.push(['CLASS STATISTICS (post-penalty)']);
    SUM.push(['Mean final score:', parseFloat(SA.formatScore(avg(penalised), rounding))]);
    SUM.push(['Min final score:',  parseFloat(SA.formatScore(min(penalised), rounding))]);
    SUM.push(['Max final score:',  parseFloat(SA.formatScore(max(penalised), rounding))]);
    SUM.push([]);

    // Tier distribution (based on suggestedGrade → tier)
    const tierCounts = { excellent: 0, proficient: 0, developing: 0, satisfactory: 0, unsatisfactory: 0 };
    const useCustomScale = Array.isArray(config.gradeScale) && config.gradeScale.length > 0;
    const tierOf = (grade) => {
      if (useCustomScale) {
        const entry = config.gradeScale.find(g => g.grade === grade);
        return entry ? entry.tier : 'developing';
      }
      return SA.GRADE_TIERS[grade] || 'developing';
    };
    cohort.students.forEach(s => {
      const g = s.scoreResult && s.scoreResult.suggestedGrade;
      const t = g ? tierOf(g) : null;
      if (t && tierCounts[t] !== undefined) tierCounts[t]++;
    });
    SUM.push(['GRADE DISTRIBUTION']);
    SUM.push([SA.getTierLabel(config, 'excellent')      + ':', tierCounts.excellent]);
    SUM.push([SA.getTierLabel(config, 'proficient')     + ':', tierCounts.proficient]);
    SUM.push([SA.getTierLabel(config, 'developing')     + ':', tierCounts.developing]);
    SUM.push([SA.getTierLabel(config, 'satisfactory')   + ':', tierCounts.satisfactory]);
    SUM.push([SA.getTierLabel(config, 'unsatisfactory') + ':', tierCounts.unsatisfactory]);

    const wsSum = XLSX.utils.aoa_to_sheet(SUM);
    wsSum['!cols'] = [{ wch: 28 }, { wch: 40 }];
    // (appended later — new tab order is Student Feedback → Grade Matrix → Cohort Summary)

    /* ── Sheet 2: Grade Matrix ────────────────────────────── */
    const MTX = [];
    const headerRow = ['Student Name', 'Student ID', 'Tutor', 'Date'];
    criteria.forEach(c => {
      headerRow.push(c.name + ' (grade)');
      headerRow.push(c.name + ' (weighted /' + c.weight + ')');
    });
    headerRow.push('Weighted Total /100');
    headerRow.push('Late Penalty');
    headerRow.push('Final Score /100');
    headerRow.push('Suggested Grade');
    headerRow.push('Override?');
    headerRow.push('Weighted /100 (pre-override)');
    headerRow.push('Pre-override Grade');
    MTX.push(headerRow);

    cohort.students.forEach(s => {
      const row = [
        s.name || '',
        s.studentId || '',
        s.tutor || '',
        s.date || ''
      ];
      const sr = s.scoreResult || {};
      const srRows = sr.rows || [];
      criteria.forEach((c, i) => {
        const srRow = srRows[i] || {};
        row.push(srRow.grade || '');
        row.push(srRow.weightedScore != null ? parseFloat(SA.formatScore(srRow.weightedScore, rounding)) : '');
      });
      row.push(sr.weightedTotal != null ? parseFloat(SA.formatScore(sr.weightedTotal, rounding)) : '');
      const lp = sr.latePenalty;
      row.push(lp ? (lp.fail ? 'Fail (late)' : (lp.deduction ? '-' + lp.deduction + '%' : 'On time')) : '');
      row.push(sr.penalisedScore != null ? parseFloat(SA.formatScore(sr.penalisedScore, rounding)) : '');
      row.push(sr.suggestedGrade || '');
      // Override audit columns
      const ov = sr.override;
      row.push(ov ? (ov.snapped ? 'Yes (bumped)' : 'Yes (letter only)') : '');
      row.push(ov && typeof ov.originalTotal === 'number'
        ? parseFloat(SA.formatScore(ov.originalTotal, rounding)) : '');
      row.push(ov ? (ov.originalGrade || '') : '');
      MTX.push(row);
    });

    // Column averages row
    const avgRow = ['CLASS AVERAGE', '', '', ''];
    criteria.forEach((c, i) => {
      avgRow.push(''); // grade column
      const vals = cohort.students.map(s => {
        const r = s.scoreResult && s.scoreResult.rows && s.scoreResult.rows[i];
        return r && typeof r.weightedScore === 'number' ? r.weightedScore : null;
      }).filter(v => v !== null);
      avgRow.push(vals.length ? parseFloat(SA.formatScore(vals.reduce((a,b)=>a+b,0)/vals.length, rounding)) : '');
    });
    avgRow.push(parseFloat(SA.formatScore(avg(totals), rounding)));
    avgRow.push('');
    avgRow.push(parseFloat(SA.formatScore(avg(penalised), rounding)));
    avgRow.push('');
    // Pad for new override columns (Override?, Weighted pre-override, Pre-override Grade)
    avgRow.push('', '', '');
    MTX.push([]);
    MTX.push(avgRow);

    const wsMtx = XLSX.utils.aoa_to_sheet(MTX);
    const mtxCols = [{ wch: 22 }, { wch: 12 }, { wch: 10 }, { wch: 14 }];
    criteria.forEach(() => { mtxCols.push({ wch: 10 }); mtxCols.push({ wch: 14 }); });
    mtxCols.push({ wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 10 }, { wch: 16 }, { wch: 22 }, { wch: 18 });
    wsMtx['!cols'] = mtxCols;
    // (appended later — new tab order is Student Feedback → Grade Matrix → Cohort Summary)

    /* ── Sheet 3: Student Feedback (one row per student) ─── */
    const FB = [];
    FB.push(['Student Name', 'Student ID', 'Tutor', 'Date', 'Suggested Grade',
             'Final Score /100', 'Cooked Feedback', "Marker's Notes"]);
    cohort.students.forEach(s => {
      const sr = s.scoreResult || {};
      FB.push([
        s.name || '',
        s.studentId || '',
        s.tutor || '',
        s.date || '',
        sr.suggestedGrade || '',
        sr.penalisedScore != null ? parseFloat(SA.formatScore(sr.penalisedScore, rounding)) : '',
        s.feedbackText || '',
        s.markerNotes || ''
      ]);
    });
    const wsFB = XLSX.utils.aoa_to_sheet(FB);
    wsFB['!cols'] = [
      { wch: 22 }, { wch: 12 }, { wch: 10 }, { wch: 14 },
      { wch: 10 }, { wch: 14 }, { wch: 80 }, { wch: 40 }
    ];
    // Append sheets in requested tab order: Student Feedback → Grade Matrix → Cohort Summary
    XLSX.utils.book_append_sheet(wb, wsFB,  'Student Feedback');
    XLSX.utils.book_append_sheet(wb, wsMtx, 'Grade Matrix');
    XLSX.utils.book_append_sheet(wb, wsSum, 'Cohort Summary');

    /* ── Sheet 4: Rubric Reference ────────────────────────── */
    const RUB = [];
    RUB.push(['RUBRIC — ' + (config.assessmentTitle || 'Assessment')]);
    RUB.push([]);
    RUB.push(['Criterion', 'Weight (%)',
              SA.getTierLabel(config, 'excellent',      { withRange: true }),
              SA.getTierLabel(config, 'proficient',     { withRange: true }),
              SA.getTierLabel(config, 'developing',     { withRange: true }),
              SA.getTierLabel(config, 'satisfactory',   { withRange: true }),
              SA.getTierLabel(config, 'unsatisfactory', { withRange: true })]);
    criteria.forEach(c => {
      RUB.push([
        c.name, c.weight,
        c.rubric.excellent || '', c.rubric.proficient || '',
        c.rubric.developing || '', c.rubric.satisfactory || '',
        c.rubric.unsatisfactory || ''
      ]);
    });
    const wsRub = XLSX.utils.aoa_to_sheet(RUB);
    wsRub['!cols'] = [{ wch: 28 }, { wch: 10 }, { wch: 45 }, { wch: 45 }, { wch: 45 }, { wch: 45 }, { wch: 45 }];
    XLSX.utils.book_append_sheet(wb, wsRub, 'Rubric');

    /* ── Sheet 5: Grade Feedback Reference ─────────────────── */
    const GF = [];
    GF.push(['GRADE FEEDBACK TEMPLATES']);
    GF.push([]);
    GF.push(['Grade', 'Intro Paragraph', 'Outro Paragraph']);
    (config.gradeFeedback || []).forEach(gf => {
      GF.push([gf.grade, gf.intro, gf.outro]);
    });
    const wsGF = XLSX.utils.aoa_to_sheet(GF);
    wsGF['!cols'] = [{ wch: 8 }, { wch: 70 }, { wch: 70 }];
    XLSX.utils.book_append_sheet(wb, wsGF, 'Grade Feedback');

    /* ── Sheet 6: Instructions ────────────────────────────── */
    const INS = [];
    INS.push(['Feedback Kitchen — Cohort Workbook']);
    INS.push(['App Version: ' + (config.appVersion || '2.0')]);
    INS.push([]);
    INS.push(['Generated by Feedback Kitchen v' + (config.appVersion || '2.0') + ' (marking.stephendmann.com)']);
    INS.push([]);
    INS.push(['Sheet', 'Contents']);
    INS.push(['Student Feedback', 'One row per student with the full cooked feedback text and marker\'s notes.']);
    INS.push(['Grade Matrix',   'One row per student showing criterion grades, weighted scores, totals, and suggested grade. Class averages at the bottom.']);
    INS.push(['Cohort Summary', 'Class-level statistics, grade distribution, cohort metadata.']);
    INS.push(['Rubric',         'The rubric descriptors used for this assessment.']);
    INS.push(['Grade Feedback', 'Intro/outro paragraphs per grade.']);
    INS.push([]);
    INS.push(['Scorer:',       config.name || '']);
    INS.push(['Cohort label:', cohort.label || '']);
    INS.push(['Students:',     cohort.students.length]);
    INS.push(['Exported:',     SA.formatDate() + ' ' + new Date().toLocaleTimeString('en-NZ')]);

    const wsIns = XLSX.utils.aoa_to_sheet(INS);
    wsIns['!cols'] = [{ wch: 22 }, { wch: 70 }];
    XLSX.utils.book_append_sheet(wb, wsIns, 'Instructions');

    /* ── Write ─────────────────────────────────────────────── */
    const safeLabel  = (cohort.label || 'Cohort').replace(/[^a-zA-Z0-9 _-]/g, '_').trim();
    const safeCourse = (config.courseName || 'Assessment').replace(/[^a-zA-Z0-9]/g, '_');
    const filename   = `${safeCourse}_${safeLabel}_Cohort.xlsx`;
    XLSX.writeFile(wb, filename);
    return filename;
  }

  window.SAExcel = { exportToExcel, exportCohortToExcel };
})();
